---
title: "poject-report"
output: html_document
date: "2025-05-22"
---

# Data Project & Hackathon 2 - Worldwide Well-being

#### Authors: [William Ambrosetti](https://github.com/WiiLife), [Alexandra Biddiscombe](https://github.com/ambiddisco), [Youssef Sedra](https://github.com/ysedra)

## 0. Abstract

We explore the idea of well-being and quality of life using different medicine-related features, through data distributed by the the WHO. We respond to questions such as "As the leader of this country, how can I improve the quality of life of my people?" and "As an unsatisfied inhabitant of this country, where can I move to have the best chance of having a healthy family and kids?".

We come to the conclusion that the well-being of a country can be modeled through a few important explanatory features and described through specific outcomes, and model what we find to be the best results of the coutries.

We approach these questions from the perspective of well-meaning but not completely informed group of aliens, visiting Earth for the first time, in an attempt to model the idea of becoming data scientists and finding ourselves in front of new and unknown situations, where we may want to make logical conclusions but do not fully understand the topic at hand.

## 1. Introduction

As students of data science, soon to be data scientists, we are expected to learn and implement decision making processes in the face of many different sources of data, and many different requests. The idea of trying to find a logical string of conclusions from a completely unknown topic is daunting, almost alien to us right now, but it is a reality of our chosen profession.

We will look at a large generalisation of data by asking and answering questions about the world as a whole, from the general idea of "What makes up the best living conditions for a person?" to the more specific "Where should I move to for the best chance at a healthy future for my family?".

## 2. Data

### 2.1 Research questions

We frame our questions as if asked by the CEO of a successful company, looking to relocate their headquarters to a new area, so as to guarantee the highest quality of life for their workers and their family.

We will frame this report around the following questions, moving from a more generic to a more specific subject:

-   What indicators can we use to determine the best country, by quality of life?
-   Which are the best countries, by quality of life?
-   Where would be the best place to move with the intent to start a family?
-   Can we corroborate our findings using the World Happiness index?

### 2.2 Data sources

The data sets we chose represent data from the WHO, found on [Kaggle](https://kaggle.com) at [World Health Statistics 2020 \| Complete \| Geo-Analysis](https://www.kaggle.com/datasets/utkarshxy/who-worldhealth-statistics-2020-complete), curated by [Zeus](https://www.kaggle.com/utkarshxy). 
We attempted to complete as much of the analysis as possible without using external data sets. 
Below are any additional data we ended up using, for additional research and validation purposes.

The data is separated into 39 different files, each of which only contains only one feature describing the state of the world, divided by country and by year. To use data like this, we need to determine which are the most relevant features for our research questions and how to evaluate them.

For one of the questions we also recovered some countries from [the World Happiness Report data](https://data.worldhappiness.report/table).

### 2.3 Data loading and cleaning

We started by selecting 22 data sets that describe well-being of the people, including medical data, accessibility to infrastructure, deaths related to a selection of causes, and similar. This data was then loaded into a single table, and labeled according to whether it is a decision - also known as explanatory - feature, or an outcome feature. What is meant by this is whether a feature can be described as a decision a country makes, such as the number of medical professionals employed, whereas outcomes indicate finality, such as deaths or the number of people that ended up catching a disease. The decision variables can also be called explanatory, as they can be used to explain how an outcome came to be, for example if we were to take the case of a person going to work: the time at which they leave their house is an explanatory feature, and the time they arrive at work is an outcome, since if they arrive late it can be explained by the fact they left late.

After choosing and separating the features, we have 22 columns divided into 11 outcomes and 9 explanatory features, plus the country and the year at which the data was recorded. The features initially had some values per 10 000 inhabitants and some per 100'000 or 1'000, so we adjusted all to be per 10'000 so the data is neater. The list of features and their meaning follows:

Outcome features:

-   **life_expectency_at_birth** : The average life expectancy of a person at birth. This value was obtained by averaging male and female values;
-   **Maternal mortality ratio (per 10 000 live births)** : The number of mothers who die during or after birth, per 10 000 people;
-   **Neonatal mortality rate (per 10 000 live births)** : The number of newborns who die in the first 28 days after birth, per 10 000 people;
-   **infant_mortality_rate** : The number of children that die between birth and 1 year after birth, per 10 000 people;
-   **under_5_mortality_rate** : The number of children that die between birth and 5 years after birth, per 10 000 people;
-   **Malaria incidence (per 10 000 population at risk)** : The number of cases of malaria per 10 000 people;
-   **Incidence of tuberculosis (per 10 000 population per year)** : The number of cases of tuberculosis per 10 000 people;
-   **hiv_infections** : The number of cases of HIV per 10 000 people;
-   **sucide_rate** : The number of people that died from suicide per 10 000 people;
-   **poison_mortality_rate** : The number of people that died from unintentional poisoning per 10 000 people;
-   **Estimated road traffic death rate (per 10 000 population)** : The number of people that died from traffic related reasons per 10 000 people.

Explanation features:

-   **Medical doctors (per 10,000)** : Medical doctors per 10 000 population;
-   **Dentists (per 10,000)** : Dentists per 10,000 population;
-   **Pharmacists (per 10,000)** : Pharmacists per 10,000 population;
-   **Nursing and midwifery personnel (per 10,000)** : Nursing and midwifery personnel per 10 000 population;
-   **Births attended by skilled health personnel (%)** : Births attended by skilled personals (percentile);
-   **Population using at least basic drinking-water services (%)** : Population using at least basic drinking water services (%);
-   **total_sanitation_services** : Population using safe sanitation services (%);
-   **basic_hand_washing_services** : Population with basic handwashing facilities at home (%);
-   **tabacco_age_15** : Prevalence of tobacco use among persons aged 15 years and older (age- standardized rate).

All data is divided and stored by country and by year:

-   **Location** : The country in which the value described was recorded;
-   **Period** : The year in which the value described was recorded.

The size of the data table is determined by the number of countries (200) and the timespan (1962 - 2019) for a total of 11'600 rows and 22 columns. Of these, 200'000 are missing values. The missing data needs to be dealt with before any real answers can be properly explored. To minimise this issue, we looked at missing data by year and removed the worst period, keeping data only after the year 2'000, then looking at the missing values per feature and choosing to reject any features with more than a limit of 3'000 missing points, set at that number to not remove too many features and still keep the data usable. This means removing 6 features, of which 5 outcomes, so to verify that we are not losing too much information we visualised some initial correlation plots between all outcome features, verifying high values of correlation between the columns to be removed and those kept, thus ensuring not too much information is lost.

We are left with the following 16 features, divided into 6 outcome, 8 explanatory and 2 that represent the country and year of the data's recording.

-   **Maternal mortality ratio (per 10 000 live births)** : The number of mothers who die during or after birth, per 10 000 people;
-   **Neonatal mortality rate (per 10 000 live births)** : The number of newborns who die in the first 28 days after birth, per 10 000 people;
-   **infant_mortality_rate** : The number of children that die between birth and 1 year after birth, per 10 000 people;
-   **under_5_mortality_rate** : The number of children that die between birth and 5 years after birth, per 10 000 people;
-   **Malaria incidence (per 10 000 population at risk)** : The number of cases of malaria per 10 000 people;
-   **Incidence of tuberculosis (per 10 000 population per year)** : The number of cases of tuberculosis per 10 000 people;

Explanation features:

-   **Medical doctors (per 10,000)** : Medical doctors per 10 000 population;
-   **Dentists (per 10,000)** : Dentists per 10,000 population;
-   **Pharmacists (per 10,000)** : Pharmacists per 10,000 population;
-   **Nursing and midwifery personnel (per 10,000)** : Nursing and midwifery personnel per 10 000 population;
-   **Births attended by skilled health personnel (%)** : Births attended by skilled personals (percentile);
-   **Population using at least basic drinking-water services (%)** : Population using at least basic drinking water services (%);
-   **total_sanitation_services** : Population using safe sanitation services (%);
-   **tabacco_age_15** : Prevalence of tobacco use among persons aged 15 years and older (age- standardized rate).

All data is still divided and stored by country and by year:

-   **Location** : The country in which the value described was recorded;
-   **Period** : The year in which the value described was recorded.

We proceeded to perform some ulterior cleaning, by normalising all the data and plotting the outliers. After noticing a strange phenomenon in number of nurses, where the number of recorded nurses in Belize approached 3'000 per 10'000 people, we decided to remove it before continuing to the rest of the exploration, because it had a negative effect on the model performances.

### 2.4 Data exploration

To inform ourselves about the general data distribution, we started by plotting the the average of each feature by year, hoping to see a linear progression towards better quality of life. This showed us that mortality rates have been steadily decreasing, access to sanitation has not had the greatest change over time, and rates of disease have slowly but surely lessened over time. From this graph we determined it was important to select some features as the most important with which to judge a country. How can we select which is the best country to live in if we cannot determine what features make up the best country? For this purpose we
