---
title: "trashy_stuff"
output: html_document
---
```{r}

# outcome features
infant_mortality_rate_data = read_csv("../data/infantMortalityRate.csv")
maternal_mortality_ratio_data = read_csv("../data/maternalMortalityRatio.csv")
life_expectency_at_birth_data = read_csv("../data/lifeExpectancyAtBirth.csv")
incidence_of_malaria_data = read_csv("../data/incedenceOfMalaria.csv")
incidence_of_tuberculosis_data = read_csv("../data/incedenceOfTuberculosis.csv")
crude_sucide_rates = read_csv("../data/crudeSuicideRates.csv")
poison_mortality_rate = read_csv("../data/mortalityRatePoisoning.csv")
neo_natal_mortality_rate = read_csv("../data/neonatalMortalityRate.csv")
new_hiv_infections = read_csv("../data/newHivInfections.csv")
road_traffic_deaths = read_csv("../data/roadTrafficDeaths.csv")
under_5_mortality_rate = read_csv("../data/under5MortalityRate.csv")
# air_pollution_death_rate = read_csv("data/airPollutionDeathRate.csv")   has too many features and is only for 2016


# decision features
medical_doctors_data = read_csv("../data/medicalDoctors.csv")
pharmacists_data = read_csv("../data/pharmacists.csv")
birth_by_skilled_personel_data = read_csv("../data/birthAttendedBySkilledPersonal.csv")
number_of_dentists = read_csv("../data/dentists.csv")
drinking_water_services = read_csv("../data/basicDrinkingWaterServices.csv")
least_basic_sanitation_services = read_csv("../data/atLeastBasicSanitizationServices.csv")
basic_hand_washing = read_csv("../data/basicHandWashing.csv")
clean_fuel_and_teck = read_csv("../data/cleanFuelAndTech.csv")
tabacco_age_15 = read_csv("../data/tobaccoAge15.csv")
nursing_services = read_csv("../data/nursingAndMidwife.csv")
sanitation_services = read_csv("../data/safelySanitization.csv")


head(medical_doctors_data, 5)
```



```{r}

# merging all the datasets into 1 taking the mean of all preiods
# replaced with bigger merged_data 

life_ex = life_expectency_at_birth_data |> group_by(Location) |> summarise(mean_life_expectancy_both_sexes=mean(`Both sexes`))
doc_at_birth = birth_by_skilled_personel_data |> group_by(Location) |> summarise(mean_doct_at_birth_perc=mean(`Births attended by skilled health personnel (%)`))

merged = full_join(life_ex, doc_at_birth, by="Location")

n_doctors = medical_doctors_data |> group_by(Location) |> summarise(mean_n_doctors_per_10000=mean(`Medical doctors (per 10,000)`))

merged = full_join(merged, n_doctors, by="Location")

n_pharmacists = pharmacists_data |> group_by(Location) |> summarise(mean_n_pharmacists_per_10000=mean(`Pharmacists  (per 10,000)`))

merged = full_join(merged, n_pharmacists, by="Location")

infant_mortality_rate = infant_mortality_rate_data |> group_by(Location) |> summarise(mean_infant_mortality_rate=mean(`Both sexes`))

merged = full_join(merged, infant_mortality_rate, by="Location")

maternal_mortality_ratio = maternal_mortality_ratio_data |> group_by(Location) |> summarise(mean_maternal_mortality_ratio_per_10000=mean(`Maternal mortality ratio (per 100 000 live births)`) / 10)

merged = full_join(merged, maternal_mortality_ratio, by="Location")

incidence_of_malaria = incidence_of_malaria_data |> group_by(Location) |> summarise(mean_incidence_malaria_per_10000=mean(`Malaria incidence (per 1 000 population at risk)`) * 10)

merged = full_join(merged, incidence_of_malaria, by="Location")

incidence_of_tuberculosis = incidence_of_tuberculosis_data |> group_by(Location) |> summarise(mean_incidence_tuberculosis_per_10000=mean(`Incidence of tuberculosis (per 100 000 population per year)`) / 10)

merged = full_join(merged, incidence_of_tuberculosis, by="Location")

```




```{r}

infant_mortality_rate_data_mutated = infant_mortality_rate_data |> select(-c(`Both sexes`)) |> pivot_longer(c(Male, Female), names_to="gender", values_to="mortality_rate") |> drop_na()

# logged density of gender infant mortality rate
infant_mortality_rate_data_mutated |> ggplot() + geom_density(aes(x=log(mortality_rate), fill=gender, alpha=0.75))

infant_mortality_rate_data_mutated_male = infant_mortality_rate_data_mutated |> filter(gender=="Male")
infant_mortality_rate_data_mutated_female = infant_mortality_rate_data_mutated |> filter(gender=="Female")

mean_m = mean(infant_mortality_rate_data_mutated_male$mortality_rate)
mean_f = mean(infant_mortality_rate_data_mutated_female$mortality_rate)

std_m = sd(infant_mortality_rate_data_mutated_male$mortality_rate)
std_f = sd(infant_mortality_rate_data_mutated_female$mortality_rate)

generated_m = rnorm(1000, mean_m, std_m)
generated_f = rnorm(1000, mean_f, std_f)

ggplot() + geom_density(aes(x=infant_mortality_rate_data_mutated_male$mortality_rate, color="red")) + geom_density(aes(x=generated_m))

ggplot() + geom_density(aes(x=infant_mortality_rate_data_mutated_female$mortality_rate, color="red")) + geom_density(aes(x=generated_f))

# the distributions are not gaussian

```

```{r}


life_expectency_at_birth_data_mutated = life_expectency_at_birth_data |> select(-c(`Both sexes`)) |> pivot_longer(c(Male, Female), names_to="gender", values_to="life_expectency") |> drop_na()

# logged density of gender infant mortality rate
life_expectency_at_birth_data_mutated |> ggplot() + geom_density(aes(x=life_expectency, fill=gender, alpha=0.75))

data_mutated_male = life_expectency_at_birth_data_mutated |> filter(gender=="Male")
data_mutated_female = life_expectency_at_birth_data_mutated |> filter(gender=="Female")

mean_m = mean(data_mutated_male$life_expectency)
mean_f = mean(data_mutated_female$life_expectency)

std_m = sd(data_mutated_male$life_expectency)
std_f = sd(data_mutated_female$life_expectency)

generated_m = rnorm(1000, mean_m, std_m)
generated_f = rnorm(1000, mean_f, std_f)

ggplot() + geom_density(aes(x=data_mutated_male$life_expectency, color="red")) + geom_density(aes(x=generated_m))

ggplot() + geom_density(aes(x=data_mutated_female$life_expectency, color="red")) + geom_density(aes(x=generated_f))

# the distributions are about gaussian

```



```{r}

# Hypothesis: Female infant mortality is the same to male infant mortality (probability of dying between birth and age 1 per 1000 live births)

# since we are using a bootstrap approach the data doesn't need to be normal

infant_mortality_rate_data_mutated = infant_mortality_rate_data |> select(-c(`Both sexes`)) |> pivot_longer(c(Male, Female), names_to="gender", values_to="mortality_rate") |> drop_na()

infant_mortality_rate_data_mutated  = infant_mortality_rate_data_mutated |> mutate(mortality_rate=log(mortality_rate))

infant_mortality_rate_data_mutated |> ggplot() + geom_boxplot(aes(x=gender, y=mortality_rate, fill=gender))

bootstrap_diff_means = infant_mortality_rate_data_mutated |> specify(explanatory=gender, response=mortality_rate) |> hypothesize(null="independence") |> generate(1000, type="bootstrap") |> calculate(stat="diff in means", order=c("Female", "Male"))
obs_mean = infant_mortality_rate_data_mutated |> specify(explanatory=gender, response=mortality_rate) |> calculate(stat="diff in means", order = c("Female", "Male"))
CI = bootstrap_diff_means |> get_confidence_interval(point_estimate=obs_mean, level = 0.95)

bootstrap_diff_means |> visualize() + shade_confidence_interval(CI) + geom_vline(xintercept=0) + labs(title="Bootstrap Distribution of Mean Difference (Female - Male)", x="Difference in Mean Infant Mortality Rate")

```

```{r}

# Hypothesis: Female have the same life expectancy at birth to males

life_expectency_at_birth_data_mutated = life_expectency_at_birth_data |> select(-c(`Both sexes`)) |> pivot_longer(c(Male, Female), names_to="gender", values_to="life_expectency") |> drop_na()

life_expectency_at_birth_data_mutated |> ggplot() + geom_boxplot(aes(x=gender, y=life_expectency, fill=gender))

bootstrap_diff_means = life_expectency_at_birth_data_mutated |> specify(explanatory=gender, response=life_expectency) |> hypothesize(null="independence") |> generate(1000, type="bootstrap") |> calculate(stat="diff in means", order=c("Female", "Male"))
obs_mean = life_expectency_at_birth_data_mutated |> specify(explanatory=gender, response=life_expectency) |> calculate(stat="diff in means", order = c("Female", "Male"))
CI = bootstrap_diff_means |> get_confidence_interval(point_estimate=obs_mean, level = 0.95)

bootstrap_diff_means |> visualize() + shade_confidence_interval(CI) + geom_vline(xintercept=0) + labs(title="Bootstrap Distribution of Mean Difference (Female - Male)", x="Difference in Mean life expectancy at birth")



```




```{r}

continents <- c(
  "Asia",                # Afghanistan
  "Europe",              # Albania
  "Africa",              # Algeria
  "Africa",              # Angola
  "North America",       # Antigua and Barbuda
  "South America",       # Argentina
  "Asia",                # Armenia
  "Oceania",             # Australia
  "Europe",              # Austria
  "Asia",                # Azerbaijan
  "North America",       # Bahamas
  "Asia",                # Bahrain
  "Asia",                # Bangladesh
  "North America",       # Barbados
  "Europe",              # Belarus
  "Europe",              # Belgium
  "North America",       # Belize
  "Africa",              # Benin
  "Asia",                # Bhutan
  "South America",       # Bolivia (Plurinational State of)
  "Europe",              # Bosnia and Herzegovina
  "Africa",              # Botswana
  "South America",       # Brazil
  "Asia",                # Brunei Darussalam
  "Europe",              # Bulgaria
  "Africa",              # Burkina Faso
  "Africa",              # Burundi
  "Africa",              # Cabo Verde
  "Asia",                # Cambodia
  "Africa",              # Cameroon
  "North America",       # Canada
  "Africa",              # Central African Republic
  "Africa",              # Chad
  "South America",       # Chile
  "Asia",                # China
  "South America",       # Colombia
  "Africa",              # Comoros
  "Africa",              # Congo
  "North America",       # Costa Rica
  "Europe",              # Croatia
  "North America",       # Cuba
  "Asia",                # Cyprus
  "Europe",              # Czechia
  "Africa",              # Côte d’Ivoire
  "Asia",                # Democratic People's Republic of Korea
  "Africa",              # Democratic Republic of the Congo
  "Europe",              # Denmark
  "Africa",              # Djibouti
  "North America",       # Dominican Republic
  "South America",       # Ecuador
  "Africa",              # Egypt
  "North America",       # El Salvador
  "Africa",              # Equatorial Guinea
  "Africa",              # Eritrea
  "Europe",              # Estonia
  "Africa",              # Eswatini
  "Africa",              # Ethiopia
  "Oceania",             # Fiji
  "Europe",              # Finland
  "Europe",              # France
  "Africa",              # Gabon
  "Africa",              # Gambia
  "Asia",                # Georgia
  "Europe",              # Germany
  "Africa",              # Ghana
  "Europe",              # Greece
  "North America",       # Grenada
  "North America",       # Guatemala
  "Africa",              # Guinea
  "Africa",              # Guinea-Bissau
  "South America",       # Guyana
  "North America",       # Haiti
  "North America",       # Honduras
  "Europe",              # Hungary
  "Europe",              # Iceland
  "Asia",                # India
  "Asia",                # Indonesia
  "Asia",                # Iran (Islamic Republic of)
  "Asia",                # Iraq
  "Europe",              # Ireland
  "Asia",                # Israel
  "Europe",              # Italy
  "North America",       # Jamaica
  "Asia",                # Japan
  "Asia",                # Jordan
  "Asia",                # Kazakhstan
  "Africa",              # Kenya
  "Oceania",             # Kiribati
  "Asia",                # Kuwait
  "Asia",                # Kyrgyzstan
  "Asia",                # Lao People's Democratic Republic
  "Europe",              # Latvia
  "Asia",                # Lebanon
  "Africa",              # Lesotho
  "Africa",              # Liberia
  "Africa",              # Libya
  "Europe",              # Lithuania
  "Europe",              # Luxembourg
  "Africa",              # Madagascar
  "Africa",              # Malawi
  "Asia",                # Malaysia
  "Asia",                # Maldives
  "Africa",              # Mali
  "Europe",              # Malta
  "Africa",              # Mauritania
  "Africa",              # Mauritius
  "North America",       # Mexico
  "Oceania",             # Micronesia (Federated States of)
  "Asia",                # Mongolia
  "Europe",              # Montenegro
  "Africa",              # Morocco
  "Africa",              # Mozambique
  "Asia",                # Myanmar
  "Africa",              # Namibia
  "Asia",                # Nepal
  "Europe",              # Netherlands
  "Oceania",             # New Zealand
  "North America",       # Nicaragua
  "Africa",              # Niger
  "Africa",              # Nigeria
  "Europe",              # Norway
  "Asia",                # Oman
  "Asia",                # Pakistan
  "North America",       # Panama
  "Oceania",             # Papua New Guinea
  "South America",       # Paraguay
  "South America",       # Peru
  "Asia",                # Philippines
  "Europe",              # Poland
  "Europe",              # Portugal
  "Asia",                # Qatar
  "Asia",                # Republic of Korea
  "Europe",              # Republic of Moldova
  "Europe",              # Romania
  "Europe",              # Russian Federation (primary)
  "Africa",              # Rwanda
  "North America",       # Saint Lucia
  "North America",       # Saint Vincent and the Grenadines
  "Oceania",             # Samoa
  "Africa",              # Sao Tome and Principe
  "Asia",                # Saudi Arabia
  "Africa",              # Senegal
  "Europe",              # Serbia
  "Africa",              # Seychelles
  "Africa",              # Sierra Leone
  "Asia",                # Singapore
  "Europe",              # Slovakia
  "Europe",              # Slovenia
  "Oceania",             # Solomon Islands
  "Africa",              # Somalia
  "Africa",              # South Africa
  "Africa",              # South Sudan
  "Europe",              # Spain
  "Asia",                # Sri Lanka
  "Africa",              # Sudan
  "Africa",              # Sudan (until 2011)
  "South America",       # Suriname
  "Europe",              # Sweden
  "Europe",              # Switzerland
  "Asia",                # Syrian Arab Republic
  "Asia",                # Tajikistan
  "Asia",                # Thailand
  "Europe",              # The former Yugoslav Republic of Macedonia
  "Asia",                # Timor-Leste
  "Africa",              # Togo
  "Oceania",             # Tonga
  "North America",       # Trinidad and Tobago
  "Africa",              # Tunisia
  "Asia",                # Turkey (primary)
  "Asia",                # Turkmenistan
  "Africa",              # Uganda
  "Europe",              # Ukraine
  "Asia",                # United Arab Emirates
  "Europe",              # United Kingdom of Great Britain and Northern Ireland
  "Africa",              # United Republic of Tanzania
  "North America",       # United States of America
  "South America",       # Uruguay
  "Asia",                # Uzbekistan
  "Oceania",             # Vanuatu
  "South America",       # Venezuela (Bolivarian Republic of)
  "Asia",                # Viet Nam
  "Asia",                # Yemen
  "Africa",              # Zambia
  "Africa",              # Zimbabwe
  "Europe",              # Andorra
  "Oceania",             # Cook Islands
  "North America",       # Dominica
  "Oceania",             # Marshall Islands
  "Oceania",             # Nauru
  "Oceania",             # Niue
  "Oceania",             # Palau
  "North America",       # Saint Kitts and Nevis
  "Asia",                # State of Palestine
  "Oceania",             # Tuvalu
  "Europe",              # Monaco
  "Europe",              # San Marino
  "Europe",              # Germany, Federal Republic (former)
  "Asia",                # India (until 1975)
  "Oceania",             # Kiribati (until 1984)
  "Asia"                 # South Viet Nam (former)
)

locations = merged$Location

continents_dict = setNames(continents, locations)

continent_list_for_merged_data = continents_dict[merged_data$Location]

# merged_data = merged_data |> mutate(continent=continent_list_for_merged_data)
```